package by.htp.committee.command;

public enum CommandName {

	AUTHORIZATION, LOCALIZATION, LOG_OUT, CHECK_RESULT, REGISTRATION, PAGINATION, MAKE_GROUP,

	GO_TO_LOGIN_PAGE, GO_TO_ADMIN_PAGE, GO_TO_MAIN_PAGE, GO_TO_ECONOMICS_REGISTRATION, GO_TO_PROGRAMMING_REGISTRATION

}
